### PR TITLE
[REM3-384] SaslClient should use AuthenticationContext with configured AuthenticationConfiguration when making a connection

### PR DESCRIPTION
**Pull request by Skyllarr**
https://issues.redhat.com/browse/REM3-384

### CODE REVIEW

**Comment by Skyllarr** [comment]
@fjuma I have updated this to use `org.wildfly.security.sasl.auth.util.AuthenticationContextSaslClientFactory` like you suggested. It works as as well. 

There are tests in wildfly-core (RemoteChannelManagementTestCase.java) that fail after this update with NoClassDefFound for AuthenticationContextSaslClientFactory. This can be resolved by adding wildfly-elytron-sasl-auth-util for the tests in that module.

Let me know what you think.

**Comment by fjuma** [comment]
Thanks, @Skyllarr. This looks good to me. Let's see what @ropalka / @fl4via think.

**Comment by Skyllarr** [comment]
@ropalka / @fl4via Please review

**Comment by Skyllarr** [comment]
Hello @fl4via / @ropalka, this is just a 1 line change that makes it possible for jboss-cli client to prompt for credentials when using `OAUTHBEARER` mechanism. Please review when you'll have time. Thanks!

**Comment by ropalka** [comment]
Hello @Skyllarr - I'll give it a try tonight - I'll run the WF test suites with your proposed changes to be sure there's no new regression. Of all will go well I'll approve and merge this PR.

**Comment by Skyllarr** [comment]
> Hello @Skyllarr - I'll give it a try tonight. I'll run the WF test suites with your proposed changes to be sure there's no new regression. When all will go well I'll approve and merge this PR.

@ropalka  Great! Thank you.

**Comment by ropalka** [comment]
All went well @Skyllarr , thanks for the PR!

**Pull request merged**
