### PR TITLE
[JBEAP-2017] Endpoint can be closed before doConnect tasks finished causing AbstractHandleableCloseable.close to wait forever

### PR DESCRIPTION
**Pull request by elguardian**
Jira upstream: https://issues.jboss.org/browse/REM3-216
Jira 7.0.0: https://issues.jboss.org/browse/JBEAP-2017

PR upstream https://github.com/jboss-remoting/jboss-remoting/pull/55

detect during authentication if the endpoint is closed.
if that's the case discards the connection.

### CODE REVIEW

**Comment by dmlloyd** [comment]
The comments on https://github.com/jboss-remoting/jboss-remoting/pull/55#discussion-diff-46041916 apply here as well.

**Comment by dmlloyd** [comment]
Please rebase this with the content from #55.

**Comment by elguardian** [comment]
@dmlloyd  rebased.

**Comment by dmlloyd** [comment]
Still showing conflicts.

**Comment by dmlloyd** [comment]
Thanks!

**Pull request merged**
