### PR TITLE
REM3-417 Typo in jboss-remoting_5_2.xsd

### PR DESCRIPTION
**Pull request by parsharma**
Issue: https://issues.redhat.com/browse/REM3-417

### CODE REVIEW

**Comment by gaol** [comment]
@fl4via would you please check ? thanks

**Comment by rachmatowicz** [comment]
Some other observations:
1. The documentation snippet for the option-type-type is incorrect.
2. The originating issue (containing the typo) was to have the ability to specify more general options on endpoints. Before the change, the limited list options (read-timeout, write-timeout, tcp-keepalive, heartbeat-interval) appeared as attributes on both the endpoint and each connection. After the change, the new options element is added as a child only on the endpoint and not added as a child on the connections, so that we still cannot specify general options per connection.

**Comment by parsharma** [comment]
Thanks for the review comment. I've updated the code according to the first point. For the second one, would you like me to create a separate issue for it?

**Comment by gaol** [comment]
@rachmatowicz would you please merge if it is good to you ? There are downstream issues depending on it. Thank you very much :)

**Pull request merged**
