### PR TITLE
Revert 63a68d07c08111119c20c305ddd1a431493c484c Change default for po…

### PR DESCRIPTION
**Pull request by baranowb**
…oled buffers back to false

### CODE REVIEW

**Comment by dmlloyd** [comment]
No, pooling should never be used as it will cause subtle memory leaks leading to OOME.

**Comment by baranowb** [comment]
This is a change in maintenance branch without proper justification.

**Comment by dmlloyd** [comment]
This is a change in a project branch, which is justified by me, the project maintainer.  Using pooled buffers *always* leaks and should *never* be done.

**Comment by baranowb** [comment]
Cool, thats all I need to know.

**Pull request closed without merging**
