### PR TITLE
Revert "[REM3-259] Authentication via remoting fail for larger requests i.e. long password"

### PR DESCRIPTION
**Pull request by panossot**
[BZ1491965] : https://bugzilla.redhat.com/show_bug.cgi?id=1491965
[REM3-308] : https://issues.jboss.org/browse/REM3-308
[Upstream] : Not required

This reverts commit e7a17c3cca653c125efc364a2e7a5f065762aeb6.

### CODE REVIEW

**Comment by TomasHofman** [comment]
Please close this one in favour of https://github.com/jboss-remoting/jboss-remoting/pull/146.

**Comment by panossot** [comment]
This I will keep open till #146 is accepted, as it also solves the issue (I cannot see the test failure described in the BZ).

**Comment by bmaxwell** [comment]
#146 is merged, so I think this one can be closed as the rework commit and the revert commit look to be merged

**Comment by panossot** [comment]
Closing this one.

**Pull request closed without merging**
